#debug: true
spring:
  application:
    name: demoStreamEventhub
  cloud:
    azure:
      eventhubs:
        connection-string: ${EVENTHUB_NAMESPACE_CONNECTION_STRING}
        processor:
          checkpoint-store:
            container-name: ${CHECKPOINT_CONTAINER}
            account-name: ${CHECKPOINT_STORAGE_ACCOUNT}
            account-key: ${CHECKPOINT_ACCESS_KEY}        
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: cg1
          group: testconsumergroup          
        supply-out-0:
          destination: cg1
      eventhubs:
        bindings:
          consume-in-0:
            checkpoint:
              mode: TIME
              interval: PT1S
      poller:
        initial-delay: 0
        fixed-delay: 1000
        
management:
  endpoints:
    web:
      exposure:
        include:
        - bindings