#debug: true
spring:
  application:
    name: demoStreamEventhub
  cloud:
    azure:
      eventhubs:
        connection-string: Endpoint=sb://eh-non-basic.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=tX4kqVRxhhjmYkLHWzm+BnuoMNbabYlMzAFA+nfTE2w=
        processor:
          checkpoint-store:
            account-name: amgstorageaccount02
            account-key: Y0fSgZvsc/z6NJ9NIVtP4VJXztaCsshV1HIEH5tYi7WFUwi5f1AfKZ2PdhWQ+AQ2zzxZcsflPbIdlwILWJSE9A==
            container-name: testcontainer03
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: cg1
          group: testconsumergroup          
        supply-out-0:
          destination: cg1
      eventhubs:
        bindings:
          consume-in-0:
            checkpoint:
              mode: TIME
              interval: PT1S
      poller:
        initial-delay: 0
        fixed-delay: 1000
        
management:
  endpoints:
    web:
      exposure:
        include:
        - bindings